#!/bin/bash

function createOrg() {
  ORG_NAME="$1" #${1}
  PORT_NUM=$2 #7054
  NUM_PEERS=$3
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/${1}.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/${1}.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:${2} --caname ca-${1} --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-${2}-ca-${1}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-${2}-ca-${1}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-${2}-ca-${1}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-${2}-ca-${1}.pem
    OrganizationalUnitIdentifier: orderer" > "${PWD}/organizations/peerOrganizations/${1}.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy ${1}'s CA cert to ${1}'s /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/${1}.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${1}.example.com/msp/tlscacerts/ca.crt"

  # Copy ${1}'s CA cert to ${1}'s /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${1}.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${1}.example.com/tlsca/tlsca.${1}.example.com-cert.pem"

  # Copy ${1}'s CA cert to ${1}'s /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${1}.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${1}.example.com/ca/ca.${1}.example.com-cert.pem"

  local cnt=0
  while [ $cnt -lt $NUM_PEERS ]
  do
    infoln "Registering peer${cnt}"
    set -x
    fabric-ca-client register --caname ca-${1} --id.name peer${cnt} --id.secret peer${cnt}pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
    { set +x; } 2>/dev/null
    cnt=$(($cnt + 1))
  done

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-${1} --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-${1} --id.name ${1}admin --id.secret ${1}adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  local cnt=0
  while [ $cnt -lt $NUM_PEERS ]
  do
    infoln "Generating the peer${cnt} msp"
    set -x
    fabric-ca-client enroll -u https://peer${cnt}:peer${cnt}pw@localhost:${2} --caname ca-${1} -M "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/msp" --csr.hosts peer${cnt}.${1}.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/${1}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/msp/config.yaml"

    infoln "Generating the peer${1}-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer${cnt}:peer${cnt}pw@localhost:${2} --caname ca-${1} -M "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls" --enrollment.profile tls --csr.hosts peer${cnt}.${1}.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
    { set +x; } 2>/dev/null


    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/${1}.example.com/peers/peer${cnt}.${1}.example.com/tls/server.key"

    cnt=$(($cnt + 1))
  done


  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:${2} --caname ca-${1} -M "${PWD}/organizations/peerOrganizations/${1}.example.com/users/User1@${1}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${1}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${1}.example.com/users/User1@${1}.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://${1}admin:${1}adminpw@localhost:${2} --caname ca-${1} -M "${PWD}/organizations/peerOrganizations/${1}.example.com/users/Admin@${1}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${1}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${1}.example.com/users/Admin@${1}.example.com/msp/config.yaml"
}